/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entidades.Jugador;
import Entidades.JugadorAcciones;
import Entidades.Universidad;
import Entidades.UniversidadAcciones;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis
 */
public class AdminJugadorForms extends javax.swing.JInternalFrame {

    private JugadorAcciones jugadores = new JugadorAcciones();
    private UniversidadAcciones universidades = new UniversidadAcciones();
    private DefaultTableModel tablaModelo;
    
    public AdminJugadorForms() {
        initComponents();
        this.tablaModelo = (DefaultTableModel) this.tablaJugadores.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboUniversidadFiltro = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Administrador de jugadores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dui", "Nombre", "Edad", "Estatura", "Peso", "Posicion", "Universidad"
            }
        ));
        jScrollPane1.setViewportView(tablaJugadores);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("Jugadores");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Filtrar:");

        jLabel3.setText("Universidad");

        comboUniversidadFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUniversidadFiltroActionPerformed(evt);
            }
        });

        jButton2.setText("Restablecer filtro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboUniversidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboUniversidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void cargarJugadores(ArrayList<Jugador> jugadoresCargados){
        this.tablaModelo.setRowCount(0);
        
        for (Jugador jugador : jugadoresCargados) {
                String[] datos = {
                    jugador.getDui(),
                    jugador.getNombre(),
                    Integer.toString(jugador.getEdad()),
                    Double.toString(jugador.getEstatura()) + " cm",
                    Double.toString(jugador.getPeso())  + " Kg",
                    jugador.getId_posicion(),
                    jugador.getId_universidad()
                };

                this.tablaModelo.addRow(datos);
            }
        
    };
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ArrayList<Universidad> universidadesCargadas = this.universidades.cargarUniversidades();
        
        this.comboUniversidadFiltro.removeAllItems();
        
        this.comboUniversidadFiltro.addItem("-- Selecciona una universidad -- ");
        
        for (Universidad universidad : universidadesCargadas) {
            this.comboUniversidadFiltro.addItem(universidad.getId_universidad());
        }
        
        cargarJugadores(this.jugadores.cargarDatos());
    }//GEN-LAST:event_formInternalFrameOpened

    private void comboUniversidadFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUniversidadFiltroActionPerformed
        this.tablaModelo.setRowCount(0);
        
        if (jugadores.filtrarJugador(this.comboUniversidadFiltro.getSelectedItem().toString()).size() > 0) {
            cargarJugadores(jugadores.filtrarJugador(this.comboUniversidadFiltro.getSelectedItem().toString()));
        }else if(!this.comboUniversidadFiltro.getSelectedItem().toString().contains("Selecciona una universidad")){
            JOptionPane.showMessageDialog(null,"La universidad selecionada no tiene jugadores");
        }else if(this.comboUniversidadFiltro.getSelectedItem().toString().contains("Selecciona una universidad")){
            this.tablaModelo.setRowCount(0);
            cargarJugadores(this.jugadores.cargarDatos());
        }
        
    }//GEN-LAST:event_comboUniversidadFiltroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarJugadores(this.jugadores.cargarDatos());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboUniversidadFiltro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaJugadores;
    // End of variables declaration//GEN-END:variables
}
